/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductCategory } from './productCategory';
import { ProductItem } from './productItem';


export interface Product { 
    control?: string;
    cost?: number;
    id?: number;
    minQuantity?: number;
    name?: string;
    price?: number;
    productCategory?: ProductCategory;
    productItems?: Array<ProductItem>;
    quantity?: number;
    status?: string;
}
