/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CashierDto } from './cashierDto';
import { ItemSaleDto } from './itemSaleDto';
import { TablesDto } from './tablesDto';


export interface SaleDto { 
    cashierDto?: CashierDto;
    change?: number;
    date?: string;
    description?: string;
    hour?: string;
    id?: number;
    itemSale?: Array<ItemSaleDto>;
    moneyRecievid?: number;
    out?: number;
    payment?: string;
    status?: string;
    tableStatus?: string;
    tablesDto?: TablesDto;
    total?: number;
}
