export * from './cashierController.service';
import { CashierControllerService } from './cashierController.service';
export * from './clientController.service';
import { ClientControllerService } from './clientController.service';
export * from './itemCategoryController.service';
import { ItemCategoryControllerService } from './itemCategoryController.service';
export * from './itemController.service';
import { ItemControllerService } from './itemController.service';
export * from './productCategoryController.service';
import { ProductCategoryControllerService } from './productCategoryController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './providerController.service';
import { ProviderControllerService } from './providerController.service';
export * from './saleController.service';
import { SaleControllerService } from './saleController.service';
export * from './tablesController.service';
import { TablesControllerService } from './tablesController.service';
export const APIS = [CashierControllerService, ClientControllerService, ItemCategoryControllerService, ItemControllerService, ProductCategoryControllerService, ProductControllerService, ProviderControllerService, SaleControllerService, TablesControllerService];
